### ISSUE TITLE
Xcode 16 Beta 4 Support, Issue with packaged LLama dependency

### ISSUE THREAD

**Issue by nickdobos** [eastriverlee/LLM.swift#30] opened 2024-07-25 17:02 UTC
Hello, when attempting to use the latest build in Xcode 16 Beta 4, I pulled the latest commit, in order to grab the recent fix from here: https://github.com/eastriverlee/LLM.swift/commit/5651e8a39309e8cb8edfdd0bee664d77caf964d3

However, by also pulling in
https://github.com/eastriverlee/LLM.swift/commit/e50b98ea3909cf269a1de3127a41b0aaa1ef7f01

I ended up with a new error that showing the included LLama.cpp interface was incompatible with this change.
"cannot be captured by an escaping closure since it is a borrowed". Somehow I ended up with a months old out of date LLama.cpp dependency reference. Even though oddly the package does seem to point towards the master branch.

I was able to fix it by manually removing this package, manually adding llama.cpp, pointed at the latest commit, and then redownloading this package. 

So I think there might need to be some fix here to how LLama is included??
Or maybe its just xcode ghosts doing weird stuff??
Figured I would share in case anyone else runs into this, but feel free to close, its not longer a blocker after my fix of manually including llama.cpp

**Comment by garfbargle** [comment] 2024-08-17 02:05
@nickdobos Grimore couldn't figure it out? :P JK. Nick, there's another branch on here called 'Pinned', it has a specific commit of Llama.cpp that fixes this. I'll put up a PR to request it to be merged. I have my separate fork where I included it.

**Comment by garfbargle** [comment] 2024-08-17 21:48
The problem is that this repo doesn't include the package.resolved and the Package.swift just specifies 'master' for llama.cpp. So, when you build the repo it just uses whatever is latest at that time. I have [PR here](https://github.com/eastriverlee/LLM.swift/pull/31) where I migrated this repo to the latest version of llama.cpp and also included the package.resolved that built successfully so you, and anyone/thing else, will build exactly the same.

**Comment by eastriverlee** [comment] 2024-08-18 05:44
mostly, removing `Package.resolved` or using `fixed` branch will solve issues like this.

reading my reply to [garfbargle](https://github.com/garfbargle)'s PR might help you understand this issue better:
> hi, thank you for your kind contribution. i know it is recommended to add `Package.resolved`, but i deliberately left out `Package.resolved` file, so that i don't have to update this every time when `llama.cpp` updates which is very frequent.
> 
> to compensate for this issue, this repo has a `fixed` branch that points to a specific commit of `llama.cpp`. people who want to use latest `llama.cpp` will just have to use `main` branch and people who want stability will use `fixed`.
> 
> if this repo is very famous, and have a lot of contributors, i may consider adding `Package.resolved` knowing that it will be updated frequently, but it isn't. i hope you understand this compromise.

**Closed as not planned by eastriverlee** 2024-08-18 05:44 UTC
Labels: question
